using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;


namespace CodeEditor2.LLM.Tools
{

    public class DocExtractor
    {
        public static string? GetDocument(string className)
        {
            foreach (string libName in LibraryPath.Keys)
            {
                if (className.StartsWith(libName))
                {
                    return getDocument(LibraryPath[libName], className);
                }
            }
            return null;
        }

        public static Dictionary<string, string> LibraryPath = new Dictionary<string, string>();

        public static string? GetDocument(Type type)
        {
            // 型が定義されているアセンブリを取得
            Assembly assembly = type.Assembly;

            // DLLのフルパスを取得
            string dllPath = assembly.Location;

            return getDocument(dllPath, type.Name);
        }
        private static string? getDocument(string dllPath, string typeName)
        {
            if (!File.Exists(dllPath)) return null;

            string xmlPath = Path.ChangeExtension(dllPath, ".xml");

            //if (!File.Exists(dllPath))
            //{
            //    return null;// Console.WriteLine("DLLファイルが見つかりません。");
            //}

            XDocument? xmlDoc = File.Exists(xmlPath) ? XDocument.Load(xmlPath) : null;
            Assembly assembly = Assembly.LoadFrom(dllPath);

            StringBuilder sb = new StringBuilder();
            sb.AppendLine($"# Library Reference: {assembly.GetName().Name}");
            sb.AppendLine($"> Generated by AgentDoc on {DateTime.Now:yyyy-MM-dd}\n");

            foreach (Type type in assembly.GetTypes().Where(t => t.IsPublic))
            {
                if (type.FullName != typeName) continue;
                sb.AppendLine($"## Class: {type.FullName}");

                // Class Summary/Remarks
                sb.AppendLine(GetFormattedXmlDocs(xmlDoc, $"T:{type.FullName}"));

                // Properties
                var props = type.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly);
                if (props.Any())
                {
                    sb.AppendLine("### Properties");
                    foreach (var prop in props)
                    {
                        sb.AppendLine(GetFormattedXmlDocs(xmlDoc, $"P:{type.FullName}.{prop.Name}"));
                        string accessors = (prop.CanRead && prop.CanWrite) ? "{ get; set; }" : (prop.CanRead ? "{ get; }" : "{ set; }");
                        sb.AppendLine($"public {GetFriendlyName(prop.PropertyType)} {prop.Name} {accessors}\n");
                    }
                }

                // Methods
                var methods = type.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
                                  .Where(m => !m.IsSpecialName); // getter/setter等を除外
                if (methods.Any())
                {
                    sb.AppendLine("### Methods");
                    foreach (var method in methods)
                    {
                        // 引数を含めたシグネチャ作成 (XML検索用)
                        string paramTypes = string.Join(",", method.GetParameters().Select(p => p.ParameterType.FullName));
                        string memberName = string.IsNullOrEmpty(paramTypes) ? $"M:{type.FullName}.{method.Name}" : $"M:{type.FullName}.{method.Name}({paramTypes})";

                        // ★ ここを修正: methodを引数に追加してパラメータ情報を取得
                        sb.AppendLine(GetFormattedXmlDocs(xmlDoc, memberName, method));

                        var paramsDisplay = string.Join(", ", method.GetParameters().Select(p => $"{GetFriendlyName(p.ParameterType)} {p.Name}"));
                        sb.AppendLine($"public {GetFriendlyName(method.ReturnType)} {method.Name}({paramsDisplay});\n");
                    }
                }
                sb.AppendLine("---\n");
            }

            //        string outputPath = Path.Combine(Path.GetDirectoryName(dllPath), $"{Path.GetFileNameWithoutExtension(dllPath)}_AgentRef.md");
            //        File.WriteAllText(outputPath, sb.ToString());
            //        Console.WriteLine($"完了！リファレンスを保存しました: {outputPath}");
            return sb.ToString();
        }
        static string GetFriendlyName(Type type)
        {
            var aliases = new Dictionary<Type, string> {
                { typeof(void), "void" }, { typeof(bool), "bool" }, { typeof(byte), "byte" },
                { typeof(char), "char" }, { typeof(decimal), "decimal" }, { typeof(double), "double" },
                { typeof(float), "float" }, { typeof(int), "int" }, { typeof(long), "long" },
                { typeof(object), "object" }, { typeof(string), "string" }
            };

            if (aliases.TryGetValue(type, out var alias)) return alias;
            if (type.IsGenericType)
            {
                var name = type.Name.Split('`')[0];
                var args = string.Join(", ", type.GetGenericArguments().Select(GetFriendlyName));
                return $"{name}<{args}>";
            }
            return type.Name;
        }

        static string GetFormattedXmlDocs(XDocument? xml, string memberName, MethodInfo method = null)
        {
            if (xml == null) return "";
            var member = xml.Descendants("member").FirstOrDefault(m => m.Attribute("name")?.Value == memberName);
            if (member == null) return "";

            var sb = new StringBuilder();
            var summary = member.Element("summary")?.Value.Trim();
            var remarks = member.Element("remarks")?.Value.Trim();

            // Summary
            if (!string.IsNullOrEmpty(summary))
                sb.AppendLine($"> **Summary:** {Regex.Replace(summary, @"\s+", " ")}  ");

            // Parameters (メソッドの場合のみ実行)
            if (method != null)
            {
                var parameters = method.GetParameters();
                foreach (var p in parameters)
                {
                    // XMLから対象の引数名(name属性)に一致するparamタグを探す
                    var paramDoc = member.Elements("param")
                        .FirstOrDefault(e => e.Attribute("name")?.Value == p.Name)?.Value.Trim();

                    if (!string.IsNullOrEmpty(paramDoc))
                    {
                        sb.AppendLine($"> - *param `{p.Name}`*: {Regex.Replace(paramDoc, @"\s+", " ")}  ");
                    }
                }
            }

            // Remarks
            if (!string.IsNullOrEmpty(remarks))
                sb.AppendLine($"> **Remarks:** {Regex.Replace(remarks, @"\s+", " ")}  ");

            return sb.ToString();
        }

    }
}